export const LAUNCH_PRODUCT_KEY = "clicky-launch"
export const FREE_TASTE_REQUEST_LIMIT = 5
export const OFFLINE_UNLOCK_GRACE_DAYS = 30
export const LAUNCH_ENTITLEMENT_DURATION_DAYS = 365
export const LAUNCH_TRIAL_INITIAL_CREDITS = 10
